# Gnomarchy default btop configuration
#
# `current.theme` is rewritten by `gnomarchy theme set`, so btop follows the
# system theme without any further configuration.
color_theme = "current"
theme_background = False
truecolor = True
vim_keys = True
rounded_corners = True
update_ms = 1000
proc_sorting = "cpu lazy"
proc_tree = False
show_battery = True
