# Gnomarchy GDM Configuration
[daemon]
WaylandEnable=true

# Uncomment to enable automatic login on encrypted installations
# AutomaticLoginEnable=true
# AutomaticLogin=@USER@

[security]

[xdmcp]

[chooser]

[debug]
